#docker-compose up
version: "3.9"
services:
  postgres:
    image: postgres:12.16
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres